### ISSUE TITLE
Leave must expire

### ISSUE THREAD

**Issue by christhonie** [christhonie/leave-application#2]
Some leave, if not taken, will expire. For instance sick leave expires prior to re-assignment in the next 3 year cycle.

Make it possible for leave entitlements to expire by adding an expireOn Date field and then write service code which will expire that leave at the right time. This is done by setting an expired Boolean field.

Implement a Scheduler which can periodically check for leave that must expire. Refer to the Movie Manager project for that example.

This must happen before people are bound to use the system, but after midnight. Cron jobs are better for this.

See https://www.baeldung.com/spring-scheduled-tasks and https://crontab.guru/

**Comment by Jason-VW** [comment]
Is this still necessary? Since we have the expiry date on LeaveEntitlement and the SQL queries/logic we used to calculate leave available used the ExpiryDate instead of the boolean value to determine if the LeaveEntitlement was expired.
